- name: Install dependencies on debian
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  loop:
    - apache2
    - libapache2-mod-php7.4

- name: Install httpd on rocky
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'
  loop:
    - httpd
    - php

- name: Install openssh
  win_chocolatey:
    name: openssh
    package_params: /SSHServerFeature
    state: present
  when: ansible_facts['os_family'] == 'Windows'

- name: Install wireshark
  win_chocolatey:
    name: wireshark
    package_params:
      - /S
      - /NCRC
      - /desktopicon=yes
      - /quicklaunchicon=yes
    state: present
  when: ansible_facts['os_family'] == 'Windows'

- name: Install libreoffice
  win_chocolatey:
    name: libreoffice-fresh
    state: present
  when: ansible_facts['os_family'] == 'Windows'
