- name: Install dependencies on debian
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  loop:
    - apache2
    - libapache2-mod-php7.4

- name: Install httpd on rocky
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'
  loop:
    - httpd
    - php
