- name: Changing ports.conf file
  ansible.builtin.template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['os_family'] == 'Debian'
  notify:
    - Reload apache service on Debian
