- name: Install apache2 on debian
  ansible.builtin.apt:
    name: apache2
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install httpd on rocky
  ansible.builtin.dnf:
    name: httpd
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'
