---

- hosts: [debian, rocky]
  become: yes
  become_user: root
  vars_files:
    - vars/firewall.yaml
  roles:
    - role: geerlingguy.firewall
    - role: download
    - role: apache

- hosts: debian
  gather_facts: no
  become: yes
  become_user: root
  roles:
    - role: php/debian

- hosts: rocky
  gather_facts: no
  become: yes
  become_user: root
  roles:
    - role: php/rocky

- hosts: self
  gather_facts: no
  become: yes
  become_user: root
  roles:
    - role: docker
