---

- hosts: [debian, rocky]
  become: yes
  become_user: root
  tags:
    - download
  roles:
    - role: download
    - role: apache

- hosts: [debian, rocky]
  become: yes
  become_user: root
  tags:
    - firewall
  vars_files:
    - vars/firewall.yaml
  roles:
    - role: geerlingguy.firewall

- hosts: debian
  gather_facts: no
  become: yes
  become_user: root
  tags:
    - apache
  roles:
    - role: php/debian

- hosts: rocky
  gather_facts: no
  become: yes
  become_user: root
  tags:
    - apache
  roles:
    - role: php/rocky

- hosts: self
  gather_facts: no
  become: yes
  become_user: root
  tags:
    - docker
  roles:
    - role: docker

- hosts: arista
  gather_facts: no
  tags:
    - arista
  roles:
    - role: arista

- hosts: windows
  gather_facts: yes
  tags:
    - windows
  roles:
    - role: deekayen.chocolatey
    - role: download
    - role: windows
