---

# Install apache
- hosts: [debian, rocky]
  become: yes
  become_user: root
  roles:
    - role: apache

- hosts: debian
  become: yes
  become_user: root
  roles:
    - role: php/debian

- hosts: rocky
  become: yes
  become_user: root
  roles:
    - role: php/rocky

- hosts: [debian, rocky]
  become: yes
  become_user: root
  roles:
    - role: reload
