---

# Install apache
- hosts: [debian, rocky]
  become: yes
  become_user: root
  roles:
    - role: download
    - role: apache

- hosts: debian
  gather_facts: no
  become: yes
  become_user: root
  roles:
    - role: php/debian

- hosts: rocky
  gather_facts: no
  become: yes
  become_user: root
  roles:
    - role: php/rocky
