---

# Install apache
- hosts: [debian, rocky]
  become: yes
  become_user: root
  roles:
    - role: apache

# Install php
- hosts: debian
  become: yes
  become_user: root
  roles:
    - role: php/debian
