---
- name: Démarrer le service Apache
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true

- name: Copier le fichier phpinfo
  ansible.builtin.copy:
    src: assets/info.php
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: 0664
